### ISSUE TITLE
ValueError: Key name must be consist only of characters, numbers and underscores

### ISSUE THREAD

**Issue by AstraLuma** [mosquito/cysystemd#35] opened 2020-12-22 04:21 UTC
Working on https://github.com/AstraLuma/mycelium/tree/eb820fa910cd5cc995a12ca5e53040b5a19219c1 and I get this back trace:

```
Dec 22 04:16:42 plants daemon.py[8163]: Traceback (most recent call last):
Dec 22 04:16:42 plants daemon.py[8163]:   File "/home/pi/mycelium/daemon.py", line 53, in <module>
Dec 22 04:16:42 plants daemon.py[8163]:     LOG.debug("config: %r", config)
Dec 22 04:16:42 plants daemon.py[8163]:   File "/usr/lib/python3.7/logging/__init__.py", line 1371, in debug
Dec 22 04:16:42 plants daemon.py[8163]:     self._log(DEBUG, msg, args, **kwargs)
Dec 22 04:16:42 plants daemon.py[8163]:   File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
Dec 22 04:16:42 plants daemon.py[8163]:     self.handle(record)
Dec 22 04:16:42 plants daemon.py[8163]:   File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
Dec 22 04:16:42 plants daemon.py[8163]:     self.callHandlers(record)
Dec 22 04:16:42 plants daemon.py[8163]:   File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
Dec 22 04:16:42 plants daemon.py[8163]:     hdlr.handle(record)
Dec 22 04:16:42 plants daemon.py[8163]:   File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
Dec 22 04:16:42 plants daemon.py[8163]:     self.emit(record)
Dec 22 04:16:42 plants daemon.py[8163]:   File "/usr/local/lib/python3.7/dist-packages/cysystemd/journal.py", line 178, in emit
Dec 22 04:16:42 plants daemon.py[8163]:     send(**data)
Dec 22 04:16:42 plants daemon.py[8163]:   File "cysystemd/_journal.pyx", line 73, in cysystemd._journal.send
Dec 22 04:16:42 plants daemon.py[8163]:   File "cysystemd/_journal.pyx", line 36, in cysystemd._journal._send
Dec 22 04:16:42 plants daemon.py[8163]: ValueError: Key name must be consist only of characters, numbers and underscores
```

cysystemd 1.4.5

**Comment by leducvin** [comment] 2021-04-01 14:07
I had the same issue, where I was calling

`logger.debug("blah blah blah: %s", some_dict)`

where `some_dict` is a dictionary with keys cysystemd doesn't like.

Changing to

`logger.debug(f"blah blah blah: {some_dict}")`

produces the same logging message but doesn't crash cysystemd.

I believe the original way I was using logger.debug was valid, but somehow crashed the cysystemd implementation. This seems to be a possible workaround.

**Comment by marchaefner** [comment] 2021-06-09 19:55
This is caused by a feature in JournaldLogHandler, where it is possible specify additional fields for the journal entry if `record.args` is a `Mapping` (e.g. `dict`). The subsequent validation of keys (and the possibly resulting error) makes sense in this context.

The relevant code: https://github.com/mosquito/cysystemd/blob/8273fdcd9fa9ccc3aedb9c947b66ba04fa8b4d5c/cysystemd/journal.py#L168-L170

A practical problem arises together with another feature, this time in the Python logging module. This makes it possible to use named substitutions in the message format string with a single `Mapping` as argument. This is done by using just the mapping in place of the whole `*args` list (which then ends up as the above `record.args`).

The relevant code (and further explanation): https://github.com/python/cpython/blob/e6e34e45222b9c7a63ba92386612acf768082ba0/Lib/logging/__init__.py#L295-L314

Together this means that whenever logging is done with a single `Mapping`, its keys have to satisfy the restrictions of field names in the journal – even in cases where it is neither required nor intended to extend the journal entry or even use named substitutions.

I found this behaviour quite surprising. I think this breaks the contract / the API as described in the documentation for the logging module:
> The msg is the message format string, and the args are the arguments which are merged into msg using the string formatting operator. (Note that this means that you can use keywords in the format string, together with a single dictionary argument.)

-----

And just to pile on the workarounds, I made this (hopefully provisional) ugliness: https://bitbucket.org/openthinclient/tcos-libs/src/1fdd2fbcbd4347932d5761c39e899ec817084c12/package-rootfs/opt/tcos-libs/libs/tcos_logging.py#lines-154:160

**Comment by brettcs** [comment] 2021-09-03 03:03
I've created a pull request that provides the narrowest possible fix for this issue: when it builds the fields dict, all keys are sanitized so any unacceptable characters are turned into underscore instead.

I'm not sure this is the best solution. Maybe we should just ignore and skip invalid keys? Maybe we should require keys to follow some particular pattern before we add them as fields to the journal record? I would be open to implementing any of those either. But this implementation seemed like the easiest way to get the ball and the discussion rolling.

**Closed** 2022-04-14 21:42 UTC

**Comment by AstraLuma** [comment] 2022-04-18 16:15
Sanitizing is probably the best solution--you're never going to get the entire python ecosystem to conform to your naming conventions.
